services:
  postgres_geo:
    image: postgis/postgis:15-3.3
    container_name: puertaApuerta_db_local
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-puertaApuerta_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: puertaApuerta_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres_geo
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-puertaApuerta_db}
      JWT_SECRET: ${JWT_SECRET:-secreto_puerta_a_puerta_2026_super_seguro}
    depends_on:
      - postgres_geo

volumes:
  postgres_data: